- .github/workflows/modernisation-platform-restart-service.yaml
CI: action to restart the delius jitbit service in supported environments
> CI: action to restart the delius jitbit service

- .github/workflows/modernisation-platform-image-build-push.yaml
Update the Jitbit version to 10.19 in the environment variable JITBIT_APP_VERSION
> Update Jitbit version to 10.19

- .github/workflows/modernisation-platform-image-build-push.yml
Downgrade Jitbit to 10.14 after application errors in production
> Downgrade Jitbit to 10.14

- .github/workflows/jitbit-build-push-all-images.yml
Add 10.23 to list of images to build
> Update jitbit-build-push-all-images.yml adding 10.23

- .github/workflows/jitbit-deploy-all-environments.yml
Update Matrix to version 10.23 for Production environment
> Upgrade Production to 10.23

- .github/workflows/jitbit-build-push-all-images.yml
Add Jitbit 10.25 to the Build options
> Add Jitbit 10.25 Build

- .github/workflows/jitbit-deploy-all-environments.yml
Update Sandbox to 10.25 latest
> Update Sandbox to 10.25 latest

- .github/workflows/enable-disable-ecs-scaling.yml
- .github/workflows/modernisation-platform-restart-service.yml
- .github/workflows/rds-autoscaling-adjust.yml
- .github/workflows/scale-ecs-env.yml
- **Update modernisation-platform-restart-service.yml**
- **add to other workflows too**
> sandbox restart

- .github/workflows/jitbit-deploy-all-environments.yml
> upgrade-test-10-25

- .github/workflows/jitbit-build-push-all-images.yml
Add latest 10.26 version of Jitbit and remove 10.23.
> Add 10.26 version

- .github/workflows/jitbit-deploy-all-environments.yml
Upgrade Sandbox to 10.26. This is the second try to do this.
> Upgrade Sandbox to 10.26

- .github/workflows/jitbit-deploy-all-environments.yml
Downgrade after failed upgrade
> Downgrade Sandbox to 10.25

- .github/workflows/jitbit-build-push-all-images.yml
> Add 10.28 version

- .github/workflows/jitbit-deploy-all-environments.yml
> Update Sandbox to 10.28 latest

- .github/workflows/jitbit-build-push-all-images.yml
Add 11.0 to the list of builds
> Update to 11.0 latest

- .github/workflows/jitbit-deploy-all-environments.yml
> Upgrade Sandbox to 11.0

- .github/workflows/jitbit-build-push-all-images.yml
Added Jitbit 11.1 version and remove 10.28 which is not deployed anywhere.
> Add 11.1 version

- .github/workflows/jitbit-deploy-all-environments.yml
Upgrade Sandbox to the latest 11.1 release
> Update Sandbox to 11.1 latest

- .github/workflows/jitbit-build-push-all-images.yml
Add 11.2 to list of builds and remove 11.0
> Update to 11.2 latest

- .github/workflows/jitbit-deploy-all-environments.yml
Upgrade Sandbox to 11.2 latest
> Update Sandbox to 11.2 latest

- .github/workflows/jitbit-deploy-all-environments.yml
> Upgrade Sandbox to 11.3

- .github/workflows/jitbit-build-push-all-images.yml
Add latest 11.4 build to list and removed 11.2
> Add Jitbit 11.4 Build

- .github/workflows/jitbit-deploy-all-environments.yml
> Update Sandbox to 11.4 latest

- .github/workflows/jitbit-deploy-all-environments.yml
> Update DEV to 11.5 latest

- .github/workflows/jitbit-deploy-all-environments.yml
> Update PreProd to 11.5 latest

- .github/workflows/jitbit-deploy-all-environments.yml
> Update Prod to 11.5

- .github/workflows/jitbit-deploy-all-environments.yml
> upgrade-test-11-5

- .github/workflows/jitbit-build-push-all-images.yml
Add Jitbit MOJ 11.7.1 Custom build
> Add Jitbit MOJ 11.7.1 Build

- .github/workflows/jitbit-deploy-all-environments.yml
Upgrade to Jitbit MOJ 11.7.1 Custom Build
> Upgrade Sandbox to 11.7.1

- .github/workflows/jitbit-deploy-all-environments.yml
Update Dev to 11.7.1 Custom build
> Update Dev to 11.7.1

- .github/workflows/jitbit-build-push-all-images.yml
> Upgrade JitBit to v11.7.2

- .github/workflows/jitbit-deploy-all-environments.yml
Sandbox update to custom MoJ v11.7.2
> Upgrade Sandbox to JitBit v11.7.2

- .github/workflows/jitbit-deploy-all-environments.yml
Updating DEV to custom MoJ v11.7.2
> Upgrade Dev to JitBit v11.7.2

- .github/workflows/jitbit-deploy-all-environments.yml
> Upgrade PreProd to JitBit v11.7.2

- .github/workflows/jitbit-deploy-all-environments.yml
Update Prod & Test to 11.7.2 Custom Build
> Update Prod & Test to 11.7.2

- .github/workflows/jitbit-deploy-all-environments.yml
> Upgrade Dev to 11.8.1 latest

- .github/workflows/jitbit-deploy-all-environments.yml
Upgrade Prod & Training to 11.8.1
> Upgrade Prod & Training to 11.8.1

- .github/workflows/jitbit-deploy-all-environments.yml
Update Prod and Test to 11.13.1
> Update Prod and Test to 11.13.1

- .github/workflows/jitbit-build-push-image-reusable.yml
- docker/Dockerfile
> Tm 1437 libpam upgrade

- .github/workflows/jitbit-deploy-all-environments.yml
Update Sandbox to the latest 11.14.1 version now PAM has been updated in the docker file
> Update Sandbox to 11.14.1
